using System.Collections.Generic;
using TheDepartmentOfCode.HtmlRenderer.Adapters.Entities;

namespace TheDepartmentOfCode.HtmlRenderer.PdfSharpCore.Utilities;

public static class W3CColorUtility
{
    private static readonly Dictionary<string, RColor> w3cColors = new Dictionary<string, RColor>
    {
        ["aliceblue"]	        = RColor.FromArgb(0xF0, 0xF8, 0xFF),
        ["antiquewhite"]        = RColor.FromArgb(0xFA, 0xEB, 0xD7),
        ["aqua"]		        = RColor.FromArgb(0x00, 0xFF, 0xFF),
        ["aquamarine"]	        = RColor.FromArgb(0x7F, 0xFF, 0xD4),
        ["azure"]		        = RColor.FromArgb(0xF0, 0xFF, 0xFF),
        ["beige"]		        = RColor.FromArgb(0xF5, 0xF5, 0xDC),
        ["bisque"]		        = RColor.FromArgb(0xFF, 0xE4, 0xC4),
        ["black"]		        = RColor.FromArgb(0x00, 0x00, 0x00),
        ["blanchedalmond"]		= RColor.FromArgb(0xFF, 0xEB, 0xCD),
        ["blue"]		        = RColor.FromArgb(0x00, 0x00, 0xFF),
        ["blueviolet"]		    = RColor.FromArgb(0x8A, 0x2B, 0xE2),
        ["brown"]		        = RColor.FromArgb(0xA5, 0x2A, 0x2A),
        ["burlywood"]		    = RColor.FromArgb(0xDE, 0xB8, 0x87),
        ["cadetblue"]		    = RColor.FromArgb(0x5F, 0x9E, 0xA0),
        ["chartreuse"]		    = RColor.FromArgb(0x7F, 0xFF, 0x00),
        ["chocolate"]		    = RColor.FromArgb(0xD2, 0x69, 0x1E),
        ["coral"]		        = RColor.FromArgb(0xFF, 0x7F, 0x50),
        ["cornflowerblue"]		= RColor.FromArgb(0x64, 0x95, 0xED),
        ["cornsilk"]		    = RColor.FromArgb(0xFF, 0xF8, 0xDC),
        ["crimson"]		        = RColor.FromArgb(0xDC, 0x14, 0x3C),
        ["cyan"]		        = RColor.FromArgb(0x00, 0xFF, 0xFF),
        ["darkblue"]		    = RColor.FromArgb(0x00, 0x00, 0x8B),
        ["darkcyan"]		    = RColor.FromArgb(0x00, 0x8B, 0x8B),
        ["darkgoldenrod"]		= RColor.FromArgb(0xB8, 0x86, 0x0B),
        ["darkgray"]		    = RColor.FromArgb(0xA9, 0xA9, 0xA9),
        ["darkgreen"]		    = RColor.FromArgb(0x00, 0x64, 0x00),
        ["darkkhaki"]		    = RColor.FromArgb(0xBD, 0xB7, 0x6B),
        ["darkmagenta"]		    = RColor.FromArgb(0x8B, 0x00, 0x8B),
        ["darkolivegreen"]		= RColor.FromArgb(0x55, 0x6B, 0x2F),
        ["darkorange"]		    = RColor.FromArgb(0xFF, 0x8C, 0x00),
        ["darkorchid"]		    = RColor.FromArgb(0x99, 0x32, 0xCC),
        ["darkred"]		        = RColor.FromArgb(0x8B, 0x00, 0x00),
        ["darksalmon"]		    = RColor.FromArgb(0xE9, 0x96, 0x7A),
        ["darkseagreen"]		= RColor.FromArgb(0x8F, 0xBC, 0x8F),
        ["darkslateblue"]		= RColor.FromArgb(0x48, 0x3D, 0x8B),
        ["darkslategray"]		= RColor.FromArgb(0x2F, 0x4F, 0x4F),
        ["darkturquoise"]		= RColor.FromArgb(0x00, 0xCE, 0xD1),
        ["darkviolet"]		    = RColor.FromArgb(0x94, 0x00, 0xD3),
        ["deeppink"]		    = RColor.FromArgb(0xFF, 0x14, 0x93),
        ["deepskyblue"]		    = RColor.FromArgb(0x00, 0xBF, 0xFF),
        ["dimgray"]		        = RColor.FromArgb(0x69, 0x69, 0x69),
        ["dodgerblue"]	        = RColor.FromArgb(0x1E, 0x90, 0xFF),
        ["firebrick"]	        = RColor.FromArgb(0xB2, 0x22, 0x22),
        ["floralwhite"]	        = RColor.FromArgb(0xFF, 0xFA, 0xF0),
        ["forestgreen"]	        = RColor.FromArgb(0x22, 0x8B, 0x22),
        ["fuchsia"]		        = RColor.FromArgb(0xFF, 0x00, 0xFF),
        ["gainsboro"]	        = RColor.FromArgb(0xDC, 0xDC, 0xDC),
        ["ghostwhite"]	        = RColor.FromArgb(0xF8, 0xF8, 0xFF),
        ["gold"]		        = RColor.FromArgb(0xFF, 0xD7, 0x00),
        ["goldenrod"]	        = RColor.FromArgb(0xDA, 0xA5, 0x20),
        ["gray"]		        = RColor.FromArgb(0x80, 0x80, 0x80),
        ["green"]		        = RColor.FromArgb(0x00, 0x80, 0x00),
        ["greenyellow"]	        = RColor.FromArgb(0xAD, 0xFF, 0x2F),
        ["honeydew"]	        = RColor.FromArgb(0xF0, 0xFF, 0xF0),
        ["hotpink"]		        = RColor.FromArgb(0xFF, 0x69, 0xB4),
        ["indianred"]	        = RColor.FromArgb(0xCD, 0x5C, 0x5C),
        ["indigo"]		        = RColor.FromArgb(0x4B, 0x00, 0x82),
        ["ivory"]		        = RColor.FromArgb(0xFF, 0xFF, 0xF0),
        ["khaki"]		        = RColor.FromArgb(0xF0, 0xE6, 0x8C),
        ["lavender"]		    = RColor.FromArgb(0xE6, 0xE6, 0xFA),
        ["lavenderblush"]		= RColor.FromArgb(0xFF, 0xF0, 0xF5),
        ["lawngreen"]		    = RColor.FromArgb(0x7C, 0xFC, 0x00),
        ["lemonchiffon"]	    = RColor.FromArgb(0xFF, 0xFA, 0xCD),
        ["lightblue"]		    = RColor.FromArgb(0xAD, 0xD8, 0xE6),
        ["lightcoral"]		    = RColor.FromArgb(0xF0, 0x80, 0x80),
        ["lightcyan"]		    = RColor.FromArgb(0xE0, 0xFF, 0xFF),
        ["lightgoldenrod"]		= RColor.FromArgb(0xFA, 0xFA, 0xD2),
        ["lightgray"]		    = RColor.FromArgb(0xD3, 0xD3, 0xD3),
        ["lightgreen"]		    = RColor.FromArgb(0x90, 0xEE, 0x90),
        ["lightpink"]		    = RColor.FromArgb(0xFF, 0xB6, 0xC1),
        ["lightsalmon"]		    = RColor.FromArgb(0xFF, 0xA0, 0x7A),
        ["lightseagreen"]		= RColor.FromArgb(0x20, 0xB2, 0xAA),
        ["lightskyblue"]		= RColor.FromArgb(0x87, 0xCE, 0xFA),
        ["lightslategray"]		= RColor.FromArgb(0x77, 0x88, 0x99),
        ["lightsteelblue"]		= RColor.FromArgb(0xB0, 0xC4, 0xDE),
        ["lightyellow"]		    = RColor.FromArgb(0xFF, 0xFF, 0xE0),
        ["lime"]		        = RColor.FromArgb(0x00, 0xFF, 0x00),
        ["limegreen"]	        = RColor.FromArgb(0x32, 0xCD, 0x32),
        ["linen"]		        = RColor.FromArgb(0xFA, 0xF0, 0xE6),
        ["magenta"]		        = RColor.FromArgb(0xFF, 0x00, 0xFF),
        ["maroon"]		        = RColor.FromArgb(0x80, 0x00, 0x00),
        ["mediumaquamarine"]	= RColor.FromArgb(0x66, 0xCD, 0xAA),
        ["mediumblue"]		    = RColor.FromArgb(0x00, 0x00, 0xCD),
        ["mediumorchid"]		= RColor.FromArgb(0xBA, 0x55, 0xD3),
        ["mediumpurple"]		= RColor.FromArgb(0x93, 0x70, 0xDB),
        ["mediumseagreen"]		= RColor.FromArgb(0x3C, 0xB3, 0x71),
        ["mediumslateblue"]		= RColor.FromArgb(0x7B, 0x68, 0xEE),
        ["mediumspringgreen"]	= RColor.FromArgb(0x00, 0xFA, 0x9A),
        ["mediumturquoise"]		= RColor.FromArgb(0x48, 0xD1, 0xCC),
        ["mediumvioletred"]		= RColor.FromArgb(0xC7, 0x15, 0x85),
        ["midnightblue"]		= RColor.FromArgb(0x19, 0x19, 0x70),
        ["mintcream"]		    = RColor.FromArgb(0xF5, 0xFF, 0xFA),
        ["mistyrose"]		    = RColor.FromArgb(0xFF, 0xE4, 0xE1),
        ["moccasin"]		    = RColor.FromArgb(0xFF, 0xE4, 0xB5),
        ["navajowhite"]		    = RColor.FromArgb(0xFF, 0xDE, 0xAD),
        ["navyblue"]		    = RColor.FromArgb(0x00, 0x00, 0x80),
        ["oldlace"]		        = RColor.FromArgb(0xFD, 0xF5, 0xE6),
        ["olive"]		        = RColor.FromArgb(0x80, 0x80, 0x00),
        ["olivedrab"]	        = RColor.FromArgb(0x6B, 0x8E, 0x23),
        ["orange"]		        = RColor.FromArgb(0xFF, 0xA5, 0x00),
        ["orangered"]		    = RColor.FromArgb(0xFF, 0x45, 0x00),
        ["orchid"]		        = RColor.FromArgb(0xDA, 0x70, 0xD6),
        ["palegoldenrod"]	    = RColor.FromArgb(0xEE, 0xE8, 0xAA),
        ["palegreen"]		    = RColor.FromArgb(0x98, 0xFB, 0x98),
        ["paleturquoise"]	    = RColor.FromArgb(0xAF, 0xEE, 0xEE),
        ["palevioletred"]	    = RColor.FromArgb(0xDB, 0x70, 0x93),
        ["papayawhip"]		    = RColor.FromArgb(0xFF, 0xEF, 0xD5),
        ["peachpuff"]		    = RColor.FromArgb(0xFF, 0xDA, 0xB9),
        ["peru"]		        = RColor.FromArgb(0xCD, 0x85, 0x3F),
        ["pink"]		        = RColor.FromArgb(0xFF, 0xC0, 0xCB),
        ["plum"]		        = RColor.FromArgb(0xDD, 0xA0, 0xDD),
        ["powderblue"]		    = RColor.FromArgb(0xB0, 0xE0, 0xE6),
        ["purple"]		        = RColor.FromArgb(0x80, 0x00, 0x80),
        ["rebeccapurple"]	    = RColor.FromArgb(0x66, 0x33, 0x99),
        ["red"]		            = RColor.FromArgb(0xFF, 0x00, 0x00),
        ["rosybrown"]		    = RColor.FromArgb(0xBC, 0x8F, 0x8F),
        ["royalblue"]		    = RColor.FromArgb(0x41, 0x69, 0xE1),
        ["saddlebrown"]		    = RColor.FromArgb(0x8B, 0x45, 0x13),
        ["salmon"]		        = RColor.FromArgb(0xFA, 0x80, 0x72),
        ["sandybrown"]		    = RColor.FromArgb(0xF4, 0xA4, 0x60),
        ["seagreen"]		    = RColor.FromArgb(0x2E, 0x8B, 0x57),
        ["seashell"]		    = RColor.FromArgb(0xFF, 0xF5, 0xEE),
        ["sienna"]		        = RColor.FromArgb(0xA0, 0x52, 0x2D),
        ["silver"]		        = RColor.FromArgb(0xC0, 0xC0, 0xC0),
        ["skyblue"]		        = RColor.FromArgb(0x87, 0xCE, 0xEB),
        ["slateblue"]		    = RColor.FromArgb(0x6A, 0x5A, 0xCD),
        ["slategray"]		    = RColor.FromArgb(0x70, 0x80, 0x90),
        ["snow"]		        = RColor.FromArgb(0xFF, 0xFA, 0xFA),
        ["springgreen"]		    = RColor.FromArgb(0x00, 0xFF, 0x7F),
        ["steelblue"]		    = RColor.FromArgb(0x46, 0x82, 0xB4),
        ["tan"]		            = RColor.FromArgb(0xD2, 0xB4, 0x8C),
        ["teal"]		        = RColor.FromArgb(0x00, 0x80, 0x80),
        ["thistle"]		        = RColor.FromArgb(0xD8, 0xBF, 0xD8),
        ["tomato"]		        = RColor.FromArgb(0xFF, 0x63, 0x47),
        ["turquoise"]	        = RColor.FromArgb(0x40, 0xE0, 0xD0),
        ["violet"]		        = RColor.FromArgb(0xEE, 0x82, 0xEE),
        ["wheat"]		        = RColor.FromArgb(0xF5, 0xDE, 0xB3),
        ["white"]		        = RColor.FromArgb(0xFF, 0xFF, 0xFF),
        ["whitesmoke"]	        = RColor.FromArgb(0xF5, 0xF5, 0xF5),
        ["yellow"]		        = RColor.FromArgb(0xFF, 0xFF, 0x00),
        ["yellowgreen"]	        = RColor.FromArgb(0x9A, 0xCD, 0x32)
    };

    public static RColor? TryParsew3CColor(
        string colorName
    )
    {
        if(
            !w3cColors.TryGetValue(
                colorName.Trim().ToLower(),
                out var result
            )
        )
        {
            return null;
        }

        return result;
    }
}