name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # NerdBank.GitVersioning needs at least as much depth as the last time
        # the version number changed to be able to correctly calculate the verison
        # number
        fetch-depth: 25
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Source/HtmlRenderer.sln
    - name: Build
      run: dotnet build --no-restore Source/HtmlRenderer.sln
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
